In [1]:
import pandas as pd
from dotenv import load_dotenv
import os
import mysql.connector

In [34]:
# Cargar variables de entorno
load_dotenv()

# Credenciales desde el archivo .env
DB_HOST = os.getenv("DB_HOST")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
def consultar_muestras_db(centroope, fecha_inicio, fecha_fin):
    """
    Consulta la base de datos para obtener los eventos de muestras filtrados por centroope y fechas.
    Retorna un DataFrame.
    """
    conexion = mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD
    )
    
    query = f"""
    SELECT 
        e.idEvento, 
        e.fecha_evento, 
        e.id_evento_tipo, 
        e.coordenada_longitud, 
        e.coordenada_latitud, 
        e.medio_contacto, 
        e.tipo_evento, 
        e.id_categoria_evento, 
        bar.id AS id_barrio, 
        bar.barrio, 
        bar.id_estrato
    FROM 
        fullclean_contactos.vwEventos e
    LEFT JOIN 
        fullclean_contactos.vwContactos con ON e.id_contacto = con.id
    LEFT JOIN 
        fullclean_contactos.barrios bar ON bar.id = con.id_barrio
    LEFT JOIN 
        fullclean_contactos.ciudades ciu ON ciu.id = con.id_ciudad
    WHERE 
        e.fecha_evento BETWEEN '{fecha_inicio} 00:00:00' AND '{fecha_fin} 23:59:59'
        AND e.id_evento_tipo in (10,53,46,63) -- = 15
        AND ciu.id_centroope = {centroope}
        AND coordenada_longitud <> 0 
        AND coordenada_latitud <> 0;
    """
    df = pd.read_sql(query, conexion)
    conexion.close()
    return df

In [35]:
conteo_eventos = df.groupby(['id_evento_tipo', 'tipo_evento']).size().reset_index(name='cantidad')
conteo_eventos
  #      AND (e.id_evento_tipo = 10 or e.id_evento_tipo = 12 or e.id_evento_tipo = 14 or e.id_evento_tipo = 53 or e.id_evento_tipo=63 or e.id_evento_tipo=46 )

   id_evento_tipo      tipo_evento  cantidad
0              15  ENTREGA MUESTRA     20092

In [36]:
df = consultar_muestras_db(2, "2024-01-01","2025-07-11")
print(df.shape)

C:\Users\hp\AppData\Local\Temp\ipykernel_19036\1976323921.py:47: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexion)

(210177, 11)

In [37]:
df["medio_contacto"].unique()

array(['GESTOR CONFIANZA', 'CONSULTOR VENTA', 'EMBAJADOR'], dtype=object)

In [ ]:
conteo_eventos = df.groupby(['id_evento_tipo', 'tipo_evento']).size().reset_index(name='cantidad')
conteo_eventos
#        AND (e.id_evento_tipo = 10 or e.id_evento_tipo = 53 or e.id_evento_tipo=63 or e.id_evento_tipo=46 )

    id_evento_tipo                          tipo_evento  cantidad
0               10                                 PAGO       228
1               11                      CAMBIO DE FECHA       189
2               13                      CAMBIO DE FECHA        83
3               15                      ENTREGA MUESTRA        32
4               16                        SIGUIENTE DIA       215
5               17                        SIGUIENTE DIA       120
6               21                            MAS TARDE        27
7               22                            MAS TARDE        57
8               40                Entregado Sin Novedad       198
9               42  Faltante o Inconsistencia Productos         1
10              45               Ya no quiere el pedido         2
11              46                   No tiene el dinero         3
12              53                        Nadie en Casa         3
13              55              Cambio de Contraentrega         3
14              56      Cliente cambia fecha de entrega         4
15              58                   Venta No Entregada         7
16              61                     Cliente de Viaje         1
17              62                     Volver a Visitar        46
18              63                              No Esta        33
19              64               Ya compro en otro lado         3
20              65                 No alcanzo el tiempo        43
21              67                        Fuera de ruta         1
22              70                        Nadie en Casa       107
23              71              Todavia Tiene Productos         6
24              72                  Cambio de Domicilio         4
25              73          No Interasado en el momento        23

In [ ]:
def cosultar_visitas_db(centroope, fecha_inicio, fecha_fin):
    """
    Consulta la base de datos para obtener los eventos de visitas filtrados por centroope y fechas.
    Retorna un DataFrame.
    """
    conexion = mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD
    )
    query = f"""
        SELECT 
            e.id_contacto,
            e.fecha_creacion,
            e.fecha_evento, 
            hour(e.fecha_evento) AS hora_evento,
            e.id_autor,
            e.coordenada_longitud, 
            e.coordenada_latitud,
            e.nombre_evento,
            e.categoria_evento,
            con.id_barrio AS id_barrio
        FROM 
            fullclean_contactos.vwEventosAgente e
        WHERE 
            e.fecha_evento BETWEEN '{fecha_inicio} 00:00:00' AND '{fecha_fin} 23:59:59'

    """
    df = pd.read_sql(query, conexion)
    conexion.close()
    return df

In [16]:
df2 =cosultar_visitas_db(2, "2025-07-11","2025-07-11")
df2.shape

C:\Users\hp\AppData\Local\Temp\ipykernel_19036\3147659282.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexion)

(267, 10)